### PR TITLE
update composer json

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
ping @SocalNick

**Comment by SocalNick** [comment]
Sorry, I'll try to get to this soon.

**Comment by SocalNick** [comment]
I actually used the following dependencies to pass tests and make my sandbox app work: https://github.com/SocalNick/ScnSocialAuth/commit/aede0cd8641404852e32aecaacb4be3dda092c45

**Comment by prolic** [comment]
thx

**Pull request closed without merging**
