### PR TITLE
Closes #182 Update user profile during authentication, when profile already exists

### LINKED ISSUE #182: Update already registered user
Hi, is there any way, how to update already registered user profile?

When user is registered, new entity is persisted in [insert method](https://github.com/SocalNick/ScnSocialAuth/blob/master/src/ScnSocialAuth/Authentication/Adapter/HybridAuth.php#L516) and `registerViaProvider` event triggered.
But when same user is authenticated with same provider, its profile is not updated. 

For example: I'll register with Facebook in some application through this module, my profile is saved. Then I'll change my email in Facebook profile and log in application again and this change is not reflected.

### PR DESCRIPTION
**Pull request by lku**

### CODE REVIEW

**Comment by SocalNick** [comment]
Hey @lku,

This looks reasonable, but I thought your original issue was the email not updating? This only appears to update the display name.

**Comment by lku** [comment]
@SocalNick Email was just an example in my original issue. It's about update whole user profile and here I forgot completely email address as you pointed out. I'll fix it immediately.

**Comment by SocalNick** [comment]
@lku - I was looking over this again and I'm not sure it works for providers that don't send an email address, i.e. Twitter. Could you look into that?

**Comment by lku** [comment]
@SocalNick Should be safe, because email address property is initialized as NULL in  [Hybrid_User_Profile class](https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/User_Profile.php#L107) and setter method for email address is defined in [ZfcUser interface](https://github.com/ZF-Commons/ZfcUser/blob/1.2.2/src/ZfcUser/Entity/UserInterface.php#L50) anyway.

**Pull request merged**
