### PR TITLE
Correcting composer.json version constraint definitions

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by SocalNick** [comment]
@Ocramius I tested this last night and it worked fine for me. What version of composer?

> You can define multiple ranges. Ranges separated by a space () or comma (,) will be treated as a logical AND.
> - https://getcomposer.org/doc/01-basic-usage.md#package-versions

**Comment by Ocramius** [comment]
@SocalNick see Roave/SecurityAdvisories#8 - installing didn't work for me either

**Comment by SocalNick** [comment]
@Ocramius - I edited my sandbox app's composer.json and everything worked fine. See https://github.com/SocalNick/ScnSocialAuth-Sandbox/commit/478f660dc3dba70844ea8615f1434e64888569ce and below.

```
 |2.0.0-p481| Nicholass-MacBook-Air in ~/workspace/ScnSocialAuth-Sandbox
±  |master ✓| → composer --version
Composer version 1.0-dev (8db7420f025b5c4705ce6f66b65c6d2b52d27813) 2015-01-12 23:02:29

 |2.0.0-p481| Nicholass-MacBook-Air in ~/workspace/ScnSocialAuth-Sandbox
±  |master ✓| → vim composer.json

 |2.0.0-p481| Nicholass-MacBook-Air in ~/workspace/ScnSocialAuth-Sandbox
±  |master ✗| → composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing zendframework/zendframework (2.3.3)
  - Installing zendframework/zendframework (2.3.4)
    Loading from cache

  - Removing zf-commons/zfc-user (1.2.1)
  - Installing zf-commons/zfc-user (1.2.2)
    Loading from cache

  - Removing socalnick/scn-social-auth (1.15.1)
  - Installing socalnick/scn-social-auth (1.15.2)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by SocalNick** [comment]
@Ocramius ok to close?

**Comment by Ocramius** [comment]
@SocalNick I guess so: thanks for checking, seems like it may be a packagist issue

**Comment by Ocramius** [comment]
@SocalNick I guess so: thanks for checking, seems like it may be a packagist issue

**Pull request closed without merging**
